//
// Autogenerated by Thrift Compiler (0.11.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var references_ttypes = require('./references_types');


var UserService = require('./UserService');
var UserServiceClient = UserService.Client;
var UserServiceProcessor = UserService.Processor;
var ttypes = require('./demo_types');
//HELPER FUNCTIONS AND STRUCTURES

var DemoService_throwException_args = function(args) {
  this.flag = null;
  if (args) {
    if (args.flag !== undefined && args.flag !== null) {
      this.flag = args.flag;
    }
  }
};
DemoService_throwException_args.prototype = {};
DemoService_throwException_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.BOOL) {
        this.flag = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

DemoService_throwException_args.prototype.write = function(output) {
  output.writeStructBegin('DemoService_throwException_args');
  if (this.flag !== null && this.flag !== undefined) {
    output.writeFieldBegin('flag', Thrift.Type.BOOL, 1);
    output.writeBool(this.flag);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var DemoService_throwException_result = function(args) {
  this.success = null;
  this.error = null;
  if (args instanceof ttypes.CustomException) {
    this.error = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
    if (args.error !== undefined && args.error !== null) {
      this.error = args.error;
    }
  }
};
DemoService_throwException_result.prototype = {};
DemoService_throwException_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.error = new ttypes.CustomException();
        this.error.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

DemoService_throwException_result.prototype.write = function(output) {
  output.writeStructBegin('DemoService_throwException_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  if (this.error !== null && this.error !== undefined) {
    output.writeFieldBegin('error', Thrift.Type.STRUCT, 1);
    this.error.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var DemoService_helloWorld_args = function(args) {
};
DemoService_helloWorld_args.prototype = {};
DemoService_helloWorld_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

DemoService_helloWorld_args.prototype.write = function(output) {
  output.writeStructBegin('DemoService_helloWorld_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var DemoService_helloWorld_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
DemoService_helloWorld_result.prototype = {};
DemoService_helloWorld_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

DemoService_helloWorld_result.prototype.write = function(output) {
  output.writeStructBegin('DemoService_helloWorld_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var DemoServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
Thrift.inherits(DemoServiceClient, UserServiceClient);
DemoServiceClient.prototype.seqid = function() { return this._seqid; };
DemoServiceClient.prototype.new_seqid = function() { return this._seqid += 1; };
DemoServiceClient.prototype.throwException = function(flag, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_throwException(flag);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_throwException(flag);
  }
};

DemoServiceClient.prototype.send_throwException = function(flag) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('throwException', Thrift.MessageType.CALL, this.seqid());
  var params = {
    flag: flag
  };
  var args = new DemoService_throwException_args(params);
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

DemoServiceClient.prototype.recv_throwException = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new DemoService_throwException_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.error) {
    return callback(result.error);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('throwException failed: unknown result');
};
DemoServiceClient.prototype.helloWorld = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_helloWorld();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_helloWorld();
  }
};

DemoServiceClient.prototype.send_helloWorld = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('helloWorld', Thrift.MessageType.CALL, this.seqid());
  var args = new DemoService_helloWorld_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

DemoServiceClient.prototype.recv_helloWorld = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new DemoService_helloWorld_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('helloWorld failed: unknown result');
};
var DemoServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler;
}
;
Thrift.inherits(DemoServiceProcessor, UserServiceProcessor);
DemoServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}
;
DemoServiceProcessor.prototype.process_throwException = function(seqid, input, output) {
  var args = new DemoService_throwException_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.throwException.length === 1) {
    Q.fcall(this._handler.throwException.bind(this._handler), args.flag)
      .then(function(result) {
        var result_obj = new DemoService_throwException_result({success: result});
        output.writeMessageBegin("throwException", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        if (err instanceof ttypes.CustomException) {
          result = new DemoService_throwException_result(err);
          output.writeMessageBegin("throwException", Thrift.MessageType.REPLY, seqid);
        } else {
          result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("throwException", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.throwException(args.flag, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined') || err instanceof ttypes.CustomException) {
        result_obj = new DemoService_throwException_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("throwException", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("throwException", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
DemoServiceProcessor.prototype.process_helloWorld = function(seqid, input, output) {
  var args = new DemoService_helloWorld_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.helloWorld.length === 0) {
    Q.fcall(this._handler.helloWorld.bind(this._handler))
      .then(function(result) {
        var result_obj = new DemoService_helloWorld_result({success: result});
        output.writeMessageBegin("helloWorld", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("helloWorld", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.helloWorld(function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new DemoService_helloWorld_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("helloWorld", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("helloWorld", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
